# Generated by Django 5.0.7 on 2024-10-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_branch_id_user_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertemp',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
