# Generated by Django 5.0.7 on 2024-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
