# Generated by Django 5.0.7 on 2024-10-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_supplier_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='lending'),
        ),
    ]
