# Generated by Django 5.0.7 on 2024-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_employee_kpi_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemp',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
