# Generated by Django 5.0.7 on 2024-10-07 12:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Order product',
                'verbose_name_plural': 'Order products',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Order service',
                'verbose_name_plural': 'Order services',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Paid')),
                ('landing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Debt')),
                ('odo_mileage', models.FloatField(blank=True, null=True, verbose_name='ODO mileage')),
                ('hev_mileage', models.FloatField(blank=True, null=True, verbose_name='HEV mileage')),
                ('ev_mileage', models.FloatField(blank=True, null=True, verbose_name='EV mileage')),
                ('manager_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Manager share')),
                ('manager_share_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Manager share percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
