# Generated by Django 5.1.1 on 2024-10-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('paid', models.FloatField(default=0, verbose_name='Paid')),
                ('landing', models.FloatField(default=0, verbose_name='Debt')),
                ('odo_mileage', models.FloatField(blank=True, null=True, verbose_name='ODO mileage')),
                ('hev_mileage', models.FloatField(blank=True, null=True, verbose_name='HEV mileage')),
                ('ev_mileage', models.FloatField(blank=True, null=True, verbose_name='EV mileage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1, verbose_name='Amount')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Order product',
                'verbose_name_plural': 'Order products',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.order')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.service')),
            ],
            options={
                'verbose_name': 'Order service',
                'verbose_name_plural': 'Order services',
            },
        ),
    ]
