# Generated by Django 5.0.7 on 2024-10-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manager_share_percentage',
        ),
    ]
