# Generated by Django 5.0.7 on 2024-10-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_order_manager_share_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderservice',
            old_name='master',
            new_name='mechanic',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='rate',
        ),
    ]
