# Generated by Django 5.0.7 on 2024-10-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_master_orderservice_mechanic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='part',
            field=models.FloatField(blank=True, null=True, verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Amount'),
        ),
    ]
