# Generated by Django 5.0.7 on 2024-10-19 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_order_manager_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount'),
        ),
    ]
