# Generated by Django 5.0.7 on 2024-10-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='landing',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Total'),
        ),
    ]
