# Generated by Django 5.0.7 on 2024-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_order_landing_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('$', 'Money')], default='%', max_length=20, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='discount_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('$', 'Money')], default='%', max_length=20, verbose_name='Discount type'),
        ),
    ]
