# Generated by Django 5.0.7 on 2024-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_orderproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='discount_type',
            field=models.CharField(choices=[('%', 'Percentage'), ('$', 'Money')], default='%', max_length=1, verbose_name='Discount type'),
        ),
    ]
