# Generated by Django 5.0.7 on 2024-10-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_orderproduct_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overall_total',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
