# Generated by Django 5.0.7 on 2024-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_order_overall_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_date',
            field=models.DateField(auto_now=True, verbose_name='Plan date'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='Start date'),
        ),
    ]
