# Generated by Django 5.0.7 on 2024-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_order_end_date_order_plan_date_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Product Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Service Total'),
        ),
    ]
