# Generated by Django 5.0.7 on 2024-11-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_order_product_total_order_service_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan_date',
            field=models.DateField(verbose_name='Plan date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
