# Generated by Django 5.0.7 on 2024-11-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_order_end_date_alter_order_plan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan_date',
            field=models.DateField(null=True, verbose_name='Plan date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
    ]
