# Generated by Django 5.0.7 on 2024-11-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_order_end_date_alter_order_plan_date_and_more'),
        ('users', '0011_alter_usertemp_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee', verbose_name='Manager'),
        ),
    ]
