# Generated by Django 5.0.7 on 2024-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='warehouse_reaminder',
            field=models.FloatField(blank=True, default=0, verbose_name='Amount'),
        ),
    ]
