# Generated by Django 5.0.7 on 2024-11-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_orderproduct_warehouse_reaminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='warehouse_reaminder',
            new_name='warehouse_remainder',
        ),
    ]
