# Generated by Django 5.0.7 on 2024-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_orderproduct_warehouse_remainder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_overall_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Product Overall Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_overall_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Service Overall Total'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='net_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Profit Total'),
        ),
    ]
