# Generated by Django 5.0.7 on 2024-10-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch ', 'verbose_name_plural': 'Branches'},
        ),
    ]
