# Generated by Django 5.0.7 on 2024-10-23 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
