# Generated by Django 5.0.7 on 2024-10-07 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('arrival_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Import price')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Export price')),
                ('min_amount', models.FloatField(default=0, verbose_name='Min amount')),
                ('max_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('state_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='State number')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is sold')),
                ('odo_mileage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ODO mileage')),
                ('hev_mileage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HEV mileage')),
                ('ev_mileage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='EV mileage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
