# Generated by Django 5.0.7 on 2024-10-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_arrival_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price'),
        ),
    ]
