# Generated by Django 5.0.7 on 2024-10-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_branch_id_product_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
