# Generated by Django 5.0.7 on 2024-11-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_car_vin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='articul',
        ),
    ]
