# Generated by Django 5.0.7 on 2024-11-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_code_product_articul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='articul',
            new_name='code',
        ),
    ]
