# Generated by Django 5.0.7 on 2024-11-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_articul_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='is_temp',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
