# Generated by Django 5.0.7 on 2024-11-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_max_discount_product_is_temp'),
        ('users', '0010_alter_employee_kpi_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year_manufacture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year manufacture'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client', verbose_name='Client id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='arrival_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Import price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Export price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supplier', verbose_name='Supplier'),
        ),
    ]
