# Generated by Django 5.0.7 on 2024-11-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_code'),
        ('users', '0011_alter_usertemp_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Import price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Export price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supplier', verbose_name='Supplier'),
        ),
    ]
