# Generated by Django 5.0.7 on 2024-10-07 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0002_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchfundtransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='debt',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_supplier', to='users.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='from_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.expensetype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='importlist',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='importlist',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='importproduct',
            name='import_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.importlist', verbose_name='Import list'),
        ),
        migrations.AddField(
            model_name='importproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='lending',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='lending',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_client', to='users.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='salary',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_employee', to='users.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='salary',
            name='from_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
