# Generated by Django 5.0.7 on 2024-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproduct',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Debt'),
        ),
    ]
