# Generated by Django 5.0.7 on 2024-10-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchfundtransfer',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='expensetype',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='importlist',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='importlist',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='importproduct',
            old_name='import_list_id',
            new_name='import_list',
        ),
        migrations.RenameField(
            model_name='importproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='lending',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='lending',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
