# Generated by Django 5.0.7 on 2024-10-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_branch_id_branchfundtransfer_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='from_user_id',
            new_name='from_user',
        ),
    ]
