# Generated by Django 5.0.7 on 2024-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_paymenttype_importlist_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15, verbose_name='Sell price'),
            preserve_default=False,
        ),
    ]
