# Generated by Django 5.0.7 on 2024-11-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_importproduct_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlist',
            name='payment_type',
            field=models.CharField(max_length=30, null=True, verbose_name='Payment Type'),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
