# Generated by Django 5.0.7 on 2024-11-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_importlist_payment_type_delete_paymenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importproduct',
            old_name='buy_price',
            new_name='arrival_price',
        ),
    ]
