# Generated by Django 5.0.7 on 2024-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_rename_buy_price_importproduct_arrival_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproduct',
            name='arrival_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Arrival price'),
        ),
    ]
