# Generated by Django 5.0.7 on 2024-11-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_importproduct_arrival_price'),
        ('users', '0011_alter_usertemp_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlist',
            name='is_initial_stock',
            field=models.BooleanField(default=False, verbose_name='Is Initial Stock'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='debt',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='paid',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='importproduct',
            name='total_summ',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='Total summ'),
        ),
    ]
