# Generated by Django 5.0.7 on 2024-11-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_importlist_is_initial_stock_alter_importlist_debt_and_more'),
        ('users', '0011_alter_usertemp_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlist',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='payment_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='importlist',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Total'),
        ),
    ]
