# Generated by Django 5.0.7 on 2024-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_importlist_debt_alter_importlist_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproduct',
            name='warehouse_reaminder',
            field=models.FloatField(blank=True, default=0, verbose_name='Amount'),
        ),
    ]
