# Generated by Django 5.0.7 on 2024-11-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_importproduct_warehouse_reaminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importproduct',
            old_name='warehouse_reaminder',
            new_name='warehouse_remainder',
        ),
    ]
