# Generated by Django 5.0.7 on 2024-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_rename_warehouse_reaminder_importproduct_warehouse_remainder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importproduct',
            name='warehouse_remainder',
        ),
        migrations.AddField(
            model_name='importproduct',
            name='warehouse_remainder_arrival_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Warehouse remainder arrival price'),
        ),
        migrations.AddField(
            model_name='importproduct',
            name='warehouse_remainder_sell_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Warehouse remainder sell price'),
        ),
    ]
